qrcodeapp/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'qrcodeapp' # Must add this here to be showed up in base.html
#

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),     # These two lines are needed to display qr code generated
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qrcodeproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('qrcodeapp.urls')),
    path('admin/', admin.site.urls),
]

qrcodeapp/models.py
from django.db import models

# Create your models here.

qrcodeapp/views.py
from django.shortcuts import render
import qrcode
import time
from django.conf import settings

def home(request):
    context = {}
    if request.method == 'POST':
        data = request.POST.get('data', '')
        img = qrcode.make(data)
        img_name = 'qr' + str(time.time()) + '.png'
        img.save(str(settings.MEDIA_ROOT) + '/' + img_name)
        return render(request, 'qrcodeapp/home.html', {'img_name': img_name})
    return render(request, 'qrcodeapp/home.html')

qrcodeapp/templates/qrcodeapp/base.html
{% load tailwind_filters %}
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
  <title>QR code generator</title>
</head>

<body>
    <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <a href="{% url 'qrcodeapp:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
              <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Django Practice</span>
          </a>
          <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
          </button>
        </div>
      </nav>
  

    <main class="p-6 mb-auto">
        {% block content %}
        {% endblock %}

        <!-- {% if user.is_authenticated %}
            <p>You are logged in as {{ request.user }}. Click here to <a href="{% url 'core:login' %}">logout</a></p>
        {% endif %} -->
    </main>

    <!-- footer -->


    <footer class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="https://flowbite.com/" class="hover:underline">QR code generator</a>. All Rights Reserved.
        </span>
    </footer>
    
    
<!-- </div> -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

</body>
</html>

qrcodeapp/templates/qrcodeapp/home.html
{% extends 'qrcodeapp/base.html' %}
{% load tailwind_filters %}
{% block title %} About {% endblock %}
{% block content %}
<div class="grid justify-items-center">
    <form action="" method="post">
        {% csrf_token %}
        <p>Generate QR code below:</p>
        {{form | crispy}}
        <br>
        <input type="text" name="data" id=""><br><br>
        <button type="submit" class="btn bg-cyan-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full flex items-center">Generate!</button>
    </form>
    <div class="qr-img">
        {% if img_name %}
            <img src="media/{{img_name}}" alt="qr code">
        {% endif %}
    </div>
</div>

{% endblock %}